# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9390d6cdd2193461f4974ec6a7c4c2bff6a396eb211b12f88a8e5a5fb7dd9fc33f5bf3c660ca080a1bd085b5ec8c38479771a12d0557de784cc42bdb45d644

test:
  secret_key_base: e4c3eb590502abd33684d4ef561bb1130f7567553a77564ac0637287f2ede2b2c09e18f0dfafa65507120ced5ebe7e179d723bc19ca67b365246cafd614c6fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
